import React from 'react';
import { render, screen } from '@testing-library/react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '../components/ui/tabs';

describe('Tabs Component A11y', () => {
    it('renders with correct ARIA roles and attributes', () => {
        render(
            <Tabs defaultValue="tab1">
                <TabsList>
                    <TabsTrigger value="tab1">Tab 1</TabsTrigger>
                    <TabsTrigger value="tab2">Tab 2</TabsTrigger>
                </TabsList>
                <TabsContent value="tab1">Content 1</TabsContent>
                <TabsContent value="tab2">Content 2</TabsContent>
            </Tabs>
        );

        // Check TabsList role
        const tabList = screen.getByRole('tablist');
        expect(tabList).toBeInTheDocument();

        // Check TabsTrigger roles and attributes
        const tab1 = screen.getByRole('tab', { name: 'Tab 1' });
        const tab2 = screen.getByRole('tab', { name: 'Tab 2' });

        expect(tab1).toHaveAttribute('aria-selected', 'true');
        expect(tab2).toHaveAttribute('aria-selected', 'false');

        // Check TabsContent role
        const panel1 = screen.getByRole('tabpanel');
        expect(panel1).toBeInTheDocument();
        expect(panel1).toHaveTextContent('Content 1');

        // Check accessibility linkage (ID refs)
        // We can't predict the exact ID generated by useId, but we can check the relationship
        const tab1Id = tab1.getAttribute('id');
        const tab1Controls = tab1.getAttribute('aria-controls');

        const panel1Id = panel1.getAttribute('id');
        const panel1LabelledBy = panel1.getAttribute('aria-labelledby');

        expect(tab1Controls).toBe(panel1Id);
        expect(panel1LabelledBy).toBe(tab1Id);

        // Check content tabIndex
        expect(panel1).toHaveAttribute('tabIndex', '0');
    });
});
