import { app, ipcMain, BrowserWindow, dialog } from 'electron';
import { validateSender } from '../utils/ipc-security';
import { accessControlService } from '../security/AccessControlService';

export function registerSystemHandlers() {
    ipcMain.handle('get-platform', (event) => {
        validateSender(event);
        return process.platform;
    });

    ipcMain.handle('get-app-version', (event) => {
        validateSender(event);
        return app.getVersion();
    });

    ipcMain.handle('privacy:toggle-protection', (event, isEnabled) => {
        validateSender(event);
        const win = BrowserWindow.fromWebContents(event.sender);
        if (win) win.setContentProtection(isEnabled);
    });

    ipcMain.handle('system:select-file', async (event, options?: { title?: string, filters?: { name: string, extensions: string[] }[] }) => {
        validateSender(event);
        const win = BrowserWindow.fromWebContents(event.sender);
        if (!win) return null;

        const result = await dialog.showOpenDialog(win, {
            title: options?.title || 'Select File',
            properties: ['openFile'],
            filters: options?.filters
        });

        if (result.canceled) return null;

        if (result.filePaths.length > 0) {
            accessControlService.grantAccess(result.filePaths[0]);
        }

        return result.filePaths[0];
    });

    ipcMain.handle('system:select-directory', async (event, options?: { title?: string }) => {
        validateSender(event);
        const win = BrowserWindow.fromWebContents(event.sender);
        if (!win) return null;

        const result = await dialog.showOpenDialog(win, {
            title: options?.title || 'Select Directory',
            properties: ['openDirectory']
        });

        if (result.canceled) return null;

        if (result.filePaths.length > 0) {
            accessControlService.grantAccess(result.filePaths[0]);
        }

        return result.filePaths[0];
    });

    ipcMain.handle('system:restart-ai', async (event) => {
        validateSender(event);
        const { DockerService } = await import('../services/DockerService');
        return await DockerService.restartSystem();
    });

    ipcMain.handle('system:save-pdf', async (event, htmlContent: string, title?: string) => {
        validateSender(event);
        const win = BrowserWindow.fromWebContents(event.sender);
        if (!win) return { success: false, error: 'Window not found' };

        // 1. Create a hidden print window
        const printWin = new BrowserWindow({
            show: false,
            webPreferences: {
                offscreen: true
            }
        });

        try {
            // 2. Load the HTML (with some basic styling)
            // Sanitize user-provided HTML to prevent script injection
            const sanitizedHtml = htmlContent
                .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
                .replace(/on\w+\s*=\s*"[^"]*"/gi, '')
                .replace(/on\w+\s*=\s*'[^']*'/gi, '');

            const styledHtml = `
                <html>
                    <head>
                        <style>
                            body { font-family: 'Inter', sans-serif; padding: 40px; line-height: 1.6; color: `#333`; }
                            h1 { border-bottom: 2px solid `#333`; padding-bottom: 10px; margin-bottom: 30px; }
                            pre { white-space: pre-wrap; }
                            .footer { margin-top: 50px; font-size: 10px; color: `#888`; border-top: 1px solid `#eee`; padding-top: 10px; }
                        </style>
                    </head>
                    <body>
                        ${sanitizedHtml}
                        <div class="footer">Generated by indiiOS Legal Assistant - ${new Date().toLocaleDateString()}</div>
                    </body>
                </html>
            `;

            await printWin.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(styledHtml)}`);

            // 3. Generate PDF data
            const pdfData = await printWin.webContents.printToPDF({
                printBackground: true,
                margins: { top: 0, bottom: 0, left: 0, right: 0 },
                pageSize: 'A4'
            });

            // 4. Ask user where to save
            const saveResult = await dialog.showSaveDialog(win, {
                title: title || 'Save Contract',
                defaultPath: `${title || 'contract'}.pdf`,
                filters: [{ name: 'PDF Documents', extensions: ['pdf'] }]
            });

            if (saveResult.canceled || !saveResult.filePath) {
                return { success: false, error: 'Save cancelled' };
            }

            // 5. Save the file
            const fs = await import('fs/promises');
            await fs.writeFile(saveResult.filePath, pdfData);

            return { success: true, filePath: saveResult.filePath };
        } catch (error) {
            console.error('[SystemHandler] PDF Generation failed:', error);
            return { success: false, error: (error as Error).message };
        } finally {
            printWin.close();
        }
    });
}

