/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { NetworkOnly } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();

cleanupOutdatedCaches();

// Precache all assets generated by vite
// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Firebase Storage images
registerRoute(
    /^https:\/\/firebasestorage\.googleapis\.com\/.*/i,
    new CacheFirst({
        cacheName: 'firebase-storage-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache Google Fonts Stylesheet
registerRoute(
    /^https:\/\/fonts\.googleapis\.com\/.*/i,
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// Cache Google Fonts Webfonts
registerRoute(
    /^https:\/\/fonts\.gstatic\.com\/.*/i,
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            }),
        ],
    })
);
// Removed Background Sync for generic API mutations.
// Firestore handles its own offline persistence and sync for data mutations.
// Using BackgroundSyncPlugin for /api/ conflicts with Firestore's built-in offline support.

// Item 385: Offline fallback for navigation requests
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkOnly({
        plugins: [
            {
                fetchDidFail: async () => {
                    return caches.match('/offline.html') as Promise<Response>;
                }
            }
        ]
    })
);

// Item 340: Push notification handler
self.addEventListener('push', (event: PushEvent) => {
    const data = event.data?.json() as { title?: string; body?: string; icon?: string } | null;
    const title = data?.title ?? 'indiiOS';
    const options: NotificationOptions = {
        body: data?.body ?? 'You have a new notification',
        icon: data?.icon ?? '/icons/icon-192x192.png',
        badge: '/favicon.svg',
    };
    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event: NotificationEvent) => {
    event.notification.close();
    event.waitUntil(
        self.clients.matchAll({ type: 'window' }).then(clients => {
            if (clients.length > 0) {
                clients[0].focus();
            } else {
                self.clients.openWindow('/');
            }
        })
    );
});

// Share Target Handler
// Intercepts POST requests from other apps sharing content
import { openDB } from 'idb';
import { logger } from '@/utils/logger';

// Item 341: Allowed MIME types and max file size for share target
const SHARE_ALLOWED_TYPES = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'audio/mpeg', 'audio/wav', 'audio/ogg', 'video/mp4', 'video/webm', 'text/plain', 'application/pdf']);
const SHARE_MAX_FILE_SIZE = 50 * 1024 * 1024; // 50MB

registerRoute(
    '/_share-target',
    async ({ request }) => {
        try {
            const formData = await request.formData();
            const files = formData.getAll('files');
            const title = formData.get('title');
            const text = formData.get('text');
            const url = formData.get('url');

            // Item 341: Validate shared files before storing
            const validatedFiles = files.filter(f => {
                if (!(f instanceof File)) return false;
                if (!SHARE_ALLOWED_TYPES.has(f.type)) return false;
                if (f.size > SHARE_MAX_FILE_SIZE) return false;
                return true;
            });

            // Store shared data in IndexedDB
            const db = await openDB('indii-share-target', 1, {
                upgrade(db) {
                    if (!db.objectStoreNames.contains('shared-items')) {
                        db.createObjectStore('shared-items', { autoIncrement: true });
                    }
                },
            });

            await db.add('shared-items', {
                files: validatedFiles,
                title,
                text,
                url,
                timestamp: Date.now(),
            });

            // Pruning mechanism: Remove items older than 24 hours
            const tx = db.transaction('shared-items', 'readwrite');
            const store = tx.objectStore('shared-items');
            let cursor = await store.openCursor();
            const oneDayAgo = Date.now() - (24 * 60 * 60 * 1000);

            while (cursor) {
                if (cursor.value.timestamp < oneDayAgo) {
                    await cursor.delete();
                }
                cursor = await cursor.continue();
            }
            await tx.done;

            // Redirect back to the app with a query param indicating a share action
            return Response.redirect('/?action=share-target', 303);
        } catch (error: unknown) {
            logger.error('[ServiceWorker] Share target error:', error);
            // Fallback redirect even on error
            return Response.redirect('/?error=share_failed', 303);
        }
    },
    'POST'
);
