
import { test, expect } from '@playwright/test';

test.describe('Maestro Campaign Workflow', () => {

  test.beforeEach(async ({ page }) => {
    // -----------------------------------------------------------------------
    // 1. Setup & Auth Bypass (Mock User)
    // -----------------------------------------------------------------------
    await page.goto('/');
    await page.waitForLoadState('domcontentloaded');

    // Wait for store to be available and mock the authenticated user
    await page.waitForFunction(() => !!(window as any).useStore);
    await page.evaluate(() => {
      const mockUser = {
        // Use the ID that triggers the memory store in MarketingService
        uid: 'maestro-user-id',
        email: 'maestro@example.com',
        displayName: 'Maestro Test User',
        emailVerified: true,
        isAnonymous: false,
        metadata: {},
        providerData: [],
        refreshToken: '',
        tenantId: null,
        delete: async () => { },
        getIdToken: async () => 'mock-token',
        getIdTokenResult: async () => ({ token: 'mock-token' } as any),
        reload: async () => { },
        toJSON: () => ({}),
        phoneNumber: null,
        photoURL: null
      };

      // Inject user and set module to 'campaign' (CampaignDashboard component)
      // This component handles post-creation selection better than the main MarketingDashboard
      // @ts-expect-error - Mocking partial store state for test
      window.useStore.setState({
        initializeAuthListener: () => () => { },
        user: mockUser,
        authLoading: false,
        currentModule: 'campaign'
      });
    });
  });

  test('should execute Agent-User Handoff: Create -> Approve -> Execute', async ({ page }) => {
    // -----------------------------------------------------------------------
    // 2. Initialize Project State (Manual Creation)
    // -----------------------------------------------------------------------

    // Check we are on Campaign Manager
    const createBtn = page.getByRole('button', { name: 'New Campaign' }).first();
    await expect(createBtn).toBeVisible();
    await createBtn.click();

    // Expect Modal Title "New Campaign"
    await expect(page.getByRole('heading', { name: 'New Campaign' }).last()).toBeVisible();

    // Fill in the "Agent's Plan"
    await page.getByTestId('campaign-title-input').fill('Dogs Having Fun');
    await page.getByTestId('campaign-description-input').fill('A viral campaign for the new hit song. Goal: Viral Awareness.');

    // Launch/Save (Simulate "Agent Proposes")
    await page.getByTestId('create-campaign-submit-btn').click();

    // -----------------------------------------------------------------------
    // 3. Verify State Transition: PLANNING -> GENERATING
    // -----------------------------------------------------------------------
    // Verify that the Detail View for "Dogs Having Fun" appears.
    await expect(page.getByRole('heading', { name: 'Dogs Having Fun' })).toBeVisible({ timeout: 10000 });

    // -----------------------------------------------------------------------
    // 4. User Review & Approval (The Handoff)
    // -----------------------------------------------------------------------
    await expect(page.getByText('Pending', { exact: false })).toBeVisible();

    // "The User Disposes" -> Click Execute (Approve)
    const executeBtn = page.getByRole('button', { name: 'Execute Campaign' });
    await expect(executeBtn).toBeVisible();
    await expect(executeBtn).toBeEnabled();

    // Click Approve
    await executeBtn.click();

    // -----------------------------------------------------------------------
    // 5. Verify Execution State
    // -----------------------------------------------------------------------
    await expect(page.getByText('Processing...')).toBeVisible();
  });

  test('should execute Agent AI Generation: Generate -> Preview -> Create -> Execute', async ({ page }) => {
    // -----------------------------------------------------------------------
    // 1. Open AI Generate Modal
    // -----------------------------------------------------------------------
    // The "AI Generate" card/button should be visible
    const aiGenerateBtn = page.getByRole('button', { name: 'Generate with AI' }).first();
    await expect(aiGenerateBtn).toBeVisible();
    await aiGenerateBtn.click();

    // verify modal open
    await expect(page.getByText('AI Campaign Generator')).toBeVisible();

    // -----------------------------------------------------------------------
    // 2. Mock AI Response
    // -----------------------------------------------------------------------
    const mockPlan = {
      title: 'AI Generated Campaign',
      description: 'Generated by E2E Test Mock',
      posts: [
        {
          platform: 'Twitter',
          day: 1,
          copy: 'Hello World from AI #testing',
          imagePrompt: 'A futuristic robot passing a test',
          hashtags: ['#testing', '#ai'],
          bestTimeToPost: '9:00 AM'
        },
        {
          platform: 'Instagram',
          day: 1,
          copy: 'Look at this amazing visual! #visuals',
          imagePrompt: 'A colorful abstract explosion',
          hashtags: ['#visuals', '#art'],
          bestTimeToPost: '12:00 PM'
        }
      ]
    };

    await page.evaluate((plan) => {
      // @ts-expect-error - injected by Playwright
      window.__MOCK_AI_PLAN__ = plan;
    }, mockPlan);

    // -----------------------------------------------------------------------
    // 3. Fill Brief & Generate
    // -----------------------------------------------------------------------
    // Fill Topic (textarea) using regex for robust placeholder matching
    await page.getByPlaceholder(/e\.g\., New album/i).fill('Test AI Topic');

    // Click Generate
    await page.getByRole('button', { name: 'Generate Campaign' }).click();

    // -----------------------------------------------------------------------
    // 4. Verify Preview State
    // -----------------------------------------------------------------------
    // Should show "Post Preview" and the Mock Title
    await expect(page.getByText('Post Preview')).toBeVisible();
    await expect(page.getByText('AI Generated Campaign')).toBeVisible();
    await expect(page.getByText('Hello World from AI #testing')).toBeVisible();

    // -----------------------------------------------------------------------
    // 5. Create & Verify Handoff
    // -----------------------------------------------------------------------
    await page.getByRole('button', { name: 'Create Campaign' }).click();

    // Should redirect to detail view with the new campaign
    await expect(page.getByRole('heading', { name: 'AI Generated Campaign' })).toBeVisible({ timeout: 10000 });

    // -----------------------------------------------------------------------
    // 6. Execute (Approve)
    // -----------------------------------------------------------------------
    const executeBtn = page.getByRole('button', { name: 'Execute Campaign' });
    await expect(executeBtn).toBeVisible();
    await executeBtn.click();

    // Verify Processing
    await expect(page.getByText('Processing...')).toBeVisible();
  });

});
