#!/bin/bash
# Auto-checkpoint: runs on every Stop event.
# Writes .agent/HANDOFF_STATE.md and pushes to the current branch.
# No manual trigger needed — this just happens.

cd "$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0

BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
DATE=$(date "+%Y-%m-%d %H:%M %Z")
COMMITS=$(git log --oneline -10 2>/dev/null || echo "none")
STATUS=$(git status --short 2>/dev/null || echo "")

mkdir -p .agent

cat > .agent/HANDOFF_STATE.md <<EOF
# Handoff State
**Updated:** $DATE
**Branch:** \`$BRANCH\`

## Recent Commits
\`\`\`
$COMMITS
\`\`\`

## Working State
\`\`\`
${STATUS:-clean working tree}
\`\`\`

---
*Auto-generated by Stop hook. Read this at session start to resume context.*
EOF

git add .agent/HANDOFF_STATE.md

# Only commit if the file actually changed
if git diff --cached --name-only | grep -q "HANDOFF_STATE.md"; then
  git commit -m "chore: session checkpoint [$(date '+%H:%M')]" .agent/HANDOFF_STATE.md 2>&1
  git push origin "$BRANCH" 2>&1 || true
fi
