import os
import time
import base64
from python.helpers.tool import Tool, Response
from python.config.ai_models import AIConfig
from google import genai
from google.genai import types

class IndiiImageGen(Tool):
    async def execute(self, **kwargs) -> Response:
        try:
            # 1. Extract Arguments
            prompt = kwargs.get("prompt", "")
            style = kwargs.get("style", "")
            aspect_ratio = kwargs.get("aspect_ratio", "1:1")
            
            if not prompt:
                return Response(message="Error: No prompt provided for image generation.", break_loop=False)

            # 2. Context Injection
            final_prompt = f"{style} {prompt}".strip() if style else prompt

            # 3. Call Gemini API
            api_key = AIConfig.get_api_key()
            client = genai.Client(api_key=api_key)
            
            self.set_progress(f"Generating image ({aspect_ratio}) with Gemini 3 Pro...")
            
            # Model selection: Centralized config
            model_name = AIConfig.IMAGE_GEN
            
            response = client.models.generate_images(
                model=model_name,
                prompt=final_prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                    aspect_ratio=aspect_ratio,
                )
            )

            if not response.generated_images:
                 return Response(message="Error: No images generated by Gemini API.", break_loop=False)

            # 4. Handle Binary Data & Save
            try:
                project_id = getattr(self.agent.context, 'id', 'default_project')
            except Exception:
                project_id = "default_project"
            
            project_root = "/a0/usr/projects"
            assets_dir = os.path.join(project_root, project_id, "assets")
            os.makedirs(assets_dir, exist_ok=True)
            
            timestamp = int(time.time())
            filename = f"gen_{timestamp}.png"
            file_path = os.path.join(assets_dir, filename)

            image_bytes = response.generated_images[0].image.image_bytes
            with open(file_path, "wb") as f:
                f.write(image_bytes)

            # 5. Return Protocol
            return Response(
                message=f"img://{file_path}",
                break_loop=False,
                additional={
                    "prompt": final_prompt,
                    "file_path": file_path,
                    "aspect_ratio": aspect_ratio
                }
            )

        except Exception as e:
            return Response(message=f"Error during image generation: {str(e)}", break_loop=False)
