import sys
import json
from pathlib import Path

def test_routing():
    """Verifies that the agent correctly routes marketing requests."""
    print("Running Marketing Routing Test...")
    
    # Path to the trace file generated by agent.py
    trace_file = Path(__file__).parents[3] / "jobs" / "conductor_trace.json"
    
    if not trace_file.exists():
        print(f"FAILURE: Trace file not found at {trace_file}")
        sys.exit(1)
        
    try:
        traces = json.loads(trace_file.read_text())
        last_trace = traces[-1]
        response = last_trace["result"]["response"]
        
        print(f"Analyzing response: {response[:100]}...")
        
        # Check if the tool was actually called
        has_tool_call = "[Tool: delegate_task]" in response
        is_marketing = "marketing" in response.lower()
        
        if has_tool_call and is_marketing:
            print("SUCCESS: Correctly routed to Marketing agent using delegate_task tool.")
            sys.exit(0)
        else:
            print(f"FAILURE: Response did not contain actual tool call. Tool call: {has_tool_call}, Is Marketing: {is_marketing}")
            sys.exit(1)
            
    except Exception as e:
        print(f"FAILURE: Error parsing trace: {e}")
        sys.exit(1)

if __name__ == "__main__":
    test_routing()
