
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths
// We are in /scripts/, so .docs is at ../.docs
const DOCS_JSON = path.resolve(__dirname, '../.docs/agent_guidelines.json');
// We want to sync to src/core/agent-guidelines.json
const CORE_JSON = path.resolve(__dirname, '../src/core/agent-guidelines.json');

export function syncAllAgents() {
    console.log('🔄 Syncing Agent Guidelines...');

    try {
        // 1. Read source
        if (!fs.existsSync(DOCS_JSON)) {
            throw new Error(`Source file not found: ${DOCS_JSON}`);
        }
        const sourceData = fs.readFileSync(DOCS_JSON, 'utf-8');
        const json = JSON.parse(sourceData);

        // 2. Simple validation
        if (!json.version || !json.agents) {
            throw new Error('Invalid agent_guidelines.json structure');
        }

        // 3. Update metadata
        const now = new Date().toISOString();
        json.lastUpdated = now;
        json._generated = true;
        json._comment = "DO NOT EDIT. This file is generated by scripts/syncAgentGuidelines.ts";

        const outputData = JSON.stringify(json, null, 2); // Pretty print with 2 spaces

        // 4. Write to core
        const coreDir = path.dirname(CORE_JSON);
        if (!fs.existsSync(coreDir)) {
            fs.mkdirSync(coreDir, { recursive: true });
        }
        fs.writeFileSync(CORE_JSON, outputData, 'utf-8');
        console.log(`✅ Synced version ${json.version} (updated ${now}) to src/core/agent-guidelines.json`);

        // 5. Write to individual agent folders
        // Derive agent directories from the JSON source
        const agentNames = json.agents.map((a: { name: string }) => a.name);

        agentNames.forEach((agentName: string) => {
            const agentDir = path.resolve(__dirname, `../src/agents/${agentName}`);
            // Ensure directory exists
            if (!fs.existsSync(agentDir)) {
                fs.mkdirSync(agentDir, { recursive: true });
            }
            const agentFile = path.join(agentDir, 'agent-guidelines.json');
            fs.writeFileSync(agentFile, outputData, 'utf-8');
            console.log(`✅ Synced to src/agents/${agentName}/agent-guidelines.json`);
        });
    } catch (error) {
        console.error('❌ Sync failed:', error);
        throw error; // Re-throw to allow caller to handle or crash
    }
}

// Always run when executed
syncAllAgents();
