/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { NetworkOnly } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();

cleanupOutdatedCaches();

// Precache all assets generated by vite
// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Firebase Storage images
registerRoute(
    /^https:\/\/firebasestorage\.googleapis\.com\/.*/i,
    new CacheFirst({
        cacheName: 'firebase-storage-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache Google Fonts Stylesheet
registerRoute(
    /^https:\/\/fonts\.googleapis\.com\/.*/i,
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// Cache Google Fonts Webfonts
registerRoute(
    /^https:\/\/fonts\.gstatic\.com\/.*/i,
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            }),
        ],
    })
);
// Background Sync for API mutations (POST, PUT, DELETE)
const bgSyncPlugin = new BackgroundSyncPlugin('offline-queue', {
    maxRetentionTime: 24 * 60, // Retry for ups to 24 Hours (in minutes)
});

registerRoute(
    /\/api\/.*/,
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'POST'
);

registerRoute(
    /\/api\/.*/,
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'PUT'
);

registerRoute(
    /\/api\/.*/,
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    }),
    'DELETE'
);
